### ISSUE TITLE
Logged out since last update (caused by Dashlane?)

### ISSUE THREAD

**Issue by LeoColomb** [Narno/Facebook-Notifier#14]
Since the last release, clicking on the button to open a new page/tab disconnect me of Facebook.
No error output, nothing to show just logged out.

I'm using Chrome 62.0.3202.75

**Comment by LeoColomb** [comment]
Ping @Narno, 'cause you're not watching the repo 😄

**Comment by Narno** [comment]
Hello @LeoColomb, I can't reproduce on Mac OSX and Windows 7 64 with the same version of Chrome... could you give more details please? Thx.

**Comment by LeoColomb** [comment]
@Narno OK, sorry, two extensions have been updated in the same time, didn't catch that.
The other one was Dashlane, to v5. When Dashlane is disabled, everything works well.
I would admit that is only related to Dashlane extension, but the bug is visible only when clicking on Facebook-Notifier button, not when accessing Facebook via omnibar or favorites...

Very weird...

**Comment by Narno** [comment]
I have just installed Dashlane and I confirm: I'm systematically disconnect when clicking on the button... :-/

**Comment by Narno** [comment]
Hum, after some tests I think the problem is related to the opened URL: `https://www.facebook.com` and `https://www.facebook.com/` are 2 differents URL for Dashlane...

**Comment by Narno** [comment]
or not... I don't understand! :-/

**Comment by Narno** [comment]
I got the same behavior when I click on "go to site" form the Dashlane app panel (on Mac OS).
<img width="456" alt="capture d ecran 2017-11-03 12 44 13" src="https://user-images.githubusercontent.com/80580/32372430-2140a6a4-c095-11e7-98e7-ff3bce3b5a87.png">

**Comment by LeoColomb** [comment]
Yes, very strange. I even don't understand how Dashlane can interfere.

**Comment by LeoColomb** [comment]
Ah good catch!

**Comment by LeoColomb** [comment]
DM from @Dashlane

> Hi Léo! The bug has been fixed and will be available today on the next extension version 5.5. Thanks for your report and patience.

**Comment by LeoColomb** [comment]
Confirmed as fixed with their plugin on version 5.5, closing.

Merci pour le suivi @Narno ! 😄

**Comment by Narno** [comment]
Yeah, good news, thanks Léo!
