### ISSUE TITLE
Blue Icon

### ISSUE THREAD

**Issue by Aleck85** [Narno/Facebook-Notifier#3]
The current icon is not contrast: it seems like a white spot on the toolbar. Please make them constantly blue.

**Comment by Narno** [comment]
Hello @Aleck85, I agree with you. I added an option to let the user choose the icon, see commit 4f4a37c5b371fce41d89d9a3a9e0ccb88c8c4e10 and release [v.0.0.12]( https://github.com/Narno/Facebook-Notifier/releases/tag/v.0.0.12).

**Comment by Narno** [comment]
Published on The Chrome Web Store: https://chrome.google.com/webstore/detail/facebook-notifier/hnhcdhgekpmjjgdfimnigdeghjhicnea.
